name: Ubuntu 22 Clang

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ubuntu-22-clang:
    runs-on: ubuntu-22.04
    name: Ubuntu-22.04-Clang
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y ninja-build clang cmake

      - name: Run CMake configuration and build
        run: |
          cmake examples -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++
          cmake --build build --parallel

      - name: Run Unit Tests
        run: ./build/tests