name: Windows MSVC

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  windows-msvc:
    runs-on: windows-latest
    name: Windows MSVC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install --no-progress --yes cmake openssl

      - name: Run CMake configuration and build
        run: |
          cmake examples -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL\" -DOPENSSL_USE_STATIC_LIBS=TRUE
          cmake --build build --parallel

      - name: Run Unit Tests
        run: .\build\tests.exe