name: Windows MSVC

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  windows-msvc:
    runs-on: windows-latest
    name: Windows MSVC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install ninja cmake --yes

      - name: Run CMake configuration and build
        run: |
          cmake examples -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build --parallel

      - name: Run Unit Tests
        run: .\build\tests.exe